### ISSUE TITLE
Could you consider creating a spin-off for meteocat?

### ISSUE THREAD

**Issue by marcgarciamarti** [kalanda/homeassistant-aemet-sensor#11]
Hi there,

loving the integration so far. Many thanks for putting it together! :)

I'm just wondering if you could easily do a spin-off so that meteocat can be also included? Meteocat has an Rest API service published here: https://apidocs.meteocat.gencat.cat/ and maybe your code can be easily extended given what you may have learnt so far while doing the AEMET integration.

I really can't code at all. That's why I'm reaching out. I see that there is already a project in github but there have only been 3 commits so far, and the last one dates back from 2019.

Many thanks for even considering it! :)

**Comment by kalanda** [comment]
If you mean this https://github.com/karasu/meteocat repository, I can see that is just a copy of my code (an old one) without anything else. About the integration of Meteocat in this project, I'm sorry but I'm not really considering it right now.

**Comment by marcgarciamarti** [comment]
Yes, I meant that. Many thanks for your prompt answer again!
