### ISSUE TITLE
En mi caso no funciona...

### ISSUE THREAD

**Issue by Polymator** [kalanda/homeassistant-aemet-sensor#12]
Seguí todos los pasos muy bien y nada...

**Comment by keiyasssss** [comment]
It's working perfeclty. Check your configuration

**Comment by AlixerVolkov** [comment]
It's not working,(error 200) v. 0.111
It was working before.

**Comment by kalanda** [comment]
It is working fine with the latest version of HA v0.111.4
**Check ALL the important notes** at docs https://github.com/kalanda/homeassistant-aemet-sensor/blob/master/README.md

For reporting any issues, please paste here you current configuration.yml **without the APIKEY** or the log where you are getting the error.

**Comment by Polymator** [comment]
sensor:
  - platform: aemet
    name: AEMET
    api_key: [ eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjZW5kcmVybzE3QGdtYWlsLmNvbSIsImp0aSI6IjBkMzNkOTg1LTQyYWYtNDZkMy04NTU5LWUxZTdlZGViMjUzNiIsImlzcyI6IkFFTUVUIiwiaWF0IjoxNTkyNjk1NjI0LCJ1c2VySWQiOiIwZDMzZDk4NS00MmFmLTQ2ZDMtODU1OS1lMWU3ZWRlYjI1MzYiLCJyb2xlIjoiIn0.bkkDqRmHLOhMPg-4ZtgeqSV64Cr9x0Gsm0P3vFzrpMg ]
    station_id: [ 0076 ]
    monitored_conditions:
      - temperature
      - humidity
      - pressure
      - precipitation
      - snow
      - visibility
      - wind_speed
      - wind_max_speed
      - wind_bearing

![image](https://user-images.githubusercontent.com/65835180/85213718-54da9700-b362-11ea-9be5-e56c219bfebd.png)

**Comment by kalanda** [comment]
Remove the `[ ]` and replace with just " at name, api_key and station_id.

For example: station_id: "0076"

**Comment by Polymator** [comment]
Gracias!! Funciona!!

**Comment by AlixerVolkov** [comment]
test with another ID station "0149X" it's not working... "0076" is working

**Comment by kalanda** [comment]
@AlixerVolkov from where did you get that ID? there are not any stations with the "0149X" at AEMET

**Comment by AlixerVolkov** [comment]
![aemet](https://user-images.githubusercontent.com/55758618/86939887-67b2e100-c142-11ea-8215-ab74ec52397d.jpg)
Look at picture is Manresa's aemet  weather station

**Comment by kalanda** [comment]
@AlixerVolkov this something wrong at AEMET side with that station. We are doing it fine, but if you click at the same tool to "Obtener" button you will get an error. That's the API side and our sensor can't do nothing to solve this. You can choose another nearest location at the list and try test if is ok. I tried with Igualada and it works.

![Captura de pantalla 2020-07-08 a las 19 50 25](https://user-images.githubusercontent.com/392687/86953371-a3ef3d00-c154-11ea-8305-aa6f6baddc4e.png)
![Captura de pantalla 2020-07-08 a las 19 51 40](https://user-images.githubusercontent.com/392687/86953376-a5b90080-c154-11ea-9cf3-53e49d6db790.png)
