### ISSUE TITLE
It,s posible to use the "municipio" XML data instead the station?

### ISSUE THREAD

**Issue by keteflips** [kalanda/homeassistant-aemet-sensor#15]
I see that the AEMET website provides climatological approximation values (I don't understand how it does the calculation) in cities without a service station, in XML format.
In my city I don't have a station and the closest one is very far away, so the values are not at all reliable, not to say useless.

Is it possible to use these values in XML?

Thank you.

**Comment by kalanda** [comment]
Could you provide a link to that file or some documentation?

**Comment by keteflips** [comment]
Of course, I can give you an example with the city Terrassa:

http://www.aemet.es/es/eltiempo/prediccion/municipios/terrassa-id08279

As you can see in the link you can get the weather prediction in XML

![image](https://user-images.githubusercontent.com/22074069/87778252-34034580-c82b-11ea-8f3c-4ec663a91340.png)

Thanks

**Comment by kalanda** [comment]
Sorry @keteflips but this data you say is about weather forecast but this component is about weather sensors. The component shows data provided from measurements at weather stations, not forecast for future conditions.
