### ISSUE TITLE
Invalid response: 200

### ISSUE THREAD

**Issue by vampirete** [kalanda/homeassistant-aemet-sensor#16]
Hola 

Estoy tratando de instalar esta integración pero no lo consigo. He seguido los pasos pero me da error, pongo aquí mi configuración de configuration.yaml ¿que puedo estar haciendo mal?

Gracias

![20200718_132126](https://user-images.githubusercontent.com/68235482/87851797-7052a680-c8fc-11ea-8a79-459bd5f406c8.jpg)

![Screenshot_20200718-132205_Home Assistant](https://user-images.githubusercontent.com/68235482/87851798-70eb3d00-c8fc-11ea-80dc-a0593dc03a8a.jpg)

![20200718_131922](https://user-images.githubusercontent.com/68235482/87851796-6df04c80-c8fc-11ea-8563-09c85494c69e.jpg)

**Comment by kalanda** [comment]
Ese número de estación no funciona porque creo que no estas cogiendo el número de tu estación del sitio correcto. Debes buscarlo en `"Observación convencional" => "Datos de observación"`como se indica en las instrucciones https://github.com/kalanda/homeassistant-aemet-sensor/blob/master/README.md

```
IMPORTANT NOTE: You have to get the station_id from "Observación convencional" => "Datos de observación" stations. It isn't the same that in "Climatologías diarias".
```
![image](https://user-images.githubusercontent.com/392687/87855888-95a2dd00-c91b-11ea-8e82-485c37d9f2a0.png)

**Comment by vampirete** [comment]
Vaya que torpe, ha funcionado, muchas gracias

**Comment by kalanda** [comment]
🥳
