### ISSUE TITLE
Excessive API request rate.

### ISSUE THREAD

**Issue by juacas** [kalanda/homeassistant-aemet-sensor#18]
I have noticed that HomeAssistant makes 4 requests every 90 seconds to the AEMET API to get the same data every time because the API only updates the values every hour.
Is it possible to increase the query interval to adapt it more to the availability of the data?
[aemetsensor.log](https://github.com/kalanda/homeassistant-aemet-sensor/files/5062375/aemetsensor.log)

**Comment by kalanda** [comment]
Thanks @juacas. This is now (finally) merged to the latest release.
