### ISSUE TITLE
 Platform error sensor.aemet after upgrade to 2021.12.XX

### ISSUE THREAD

**Issue by inigoml** [kalanda/homeassistant-aemet-sensor#24]
Version: 2021.12.3

Alfter upgrade, AEMET sensor does not work anymore:

This is due to this change in HA.
home-assistant/core#58380

![image](https://user-images.githubusercontent.com/7486708/146752581-74311fa1-b6a7-4acf-b8b6-9b8aa79b38d9.png)

**Comment by kalanda** [comment]
@inigoml Home Assistant now has native support for AEMET, so I've decided to stop this component development. You don't need this anymore.
https://www.home-assistant.io/integrations/aemet/

**Comment by inigoml** [comment]
Cool.  Pity because I had finished the fix. :-)
Thank you!
