### ISSUE TITLE
Call to API is out of date?

### ISSUE THREAD

**Issue by conectaxp** [kalanda/homeassistant-aemet-sensor#4]
I think component is not runnig because API is out of date. Is possible?

Sorry, my English is not good :-(

**Comment by domologyes** [comment]
No es un problema de la librería si no del ID de la estación.
Cuando vamos a buscar el ID de la estación al "Acceso General" de Opendata de la AEMET, por "logico" y porque en alguna web así lo comunica, buscamos la estación en "Climatologías diarias".
Sin embargo, este componente usa "Observación convencional" => "Datos de observación". Las estaciones no coinciden con las de Climatología Diaria.

Como ejemplo, tomando Granada como provincia, si vamos a "Acceso General" -> "Climatologías diarias" para averiguar el ID de estacion, salen varias, entre las que esta por ej. 5514 Granada-Base aerea. Al meter este ID de estacion en el sensor, no devuelve datos.
Si ahora vamos a "Observación convencional" => "Datos de observación" vemos que la estación 5514 no está, y sin embargo está la 5515X que no está en la primera sección.

Por tanto y en resumen para obtener el ID de la estación a usar en el componente tenemos que usar  "Observación convencional" => "Datos de observación"

**Comment by domologyes** [comment]
I resume in English previous:
Library is ok. Station ID problem.
You have to use  "Observación convencional" => "Datos de observación" stations. It isn't the same that in "Climatologías diarias".

**Comment by conectaxp** [comment]
> Por tanto y en resumen para obtener el ID de la estación a usar en el componente tenemos que usar "Observación convencional" => "Datos de observación"

Efectivamente, era ese el problema. Las pruebas que yo estuve haciendo para localizar el problema las estaba haciendo sobre la API equivocada :-(

Ahora me queda una cosa más. Home Assistant me lanza este error: "dh key too small". Lo he solucionado comentando la línea "CipherString = DEFAULT@SECLEVEL=2" en /etc/ssl/openssl.cnf. Entiendo que es un problema de la API y no tuyo, pero... ¿es la manera de solucionarlo o hay otra mejor?

Tengo Raspbian Buster y Home Assistant 0.98.1

Muchas gracias por tu atención :-)

**Comment by kalanda** [comment]
@conectaxp @domologyes llego tarde por aquí y veo que ya lo habéis solucionado :) así que cierro issue
