### ISSUE TITLE
No info retrieved on Hass.IO 0.98.3

### ISSUE THREAD

**Issue by ZapaMan** [kalanda/homeassistant-aemet-sensor#5]
Hi,
After installing and configuring, it seems like the sensor is not retrieving any info. When checking "developer tools" log on Hass.IO, the error reads "Invalid response: 200".
Both api_key and station_id are correctly configured on _configuration.yaml_

**Comment by kalanda** [comment]
Comprueba que el `station_id` sea el correcto. Mira este comentario de @domologyes
https://github.com/kalanda/homeassistant-aemet-sensor/issues/4#issuecomment-526479813

**Comment by ZapaMan** [comment]
Correcto, siguiendo ese comentario ya arroja datos.
Muchas gracias!

**Comment by kalanda** [comment]
Genial!! he añadido una nota al README.md para que a otros no les pase. Gracias por el aviso.

**Comment by ZapaMan** [comment]
De nada! Muchas gracias a ti!
